(async () => {
    console.log('Hello world!');
})().catch(err => console.error(err));
